name: joinus
description: "A so cool app."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  crypto: ^3.0.6
  table_calendar: ^3.2.0
  uuid: ^4.5.1
  google_sign_in: ^6.3.0
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
